[project]
name = "ros-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "freshmea", email = "freshmea@naver.com" }
]
requires-python = ">=3.12"
dependencies = [
    "opencv-stubs==0.1.3",
]

[project.scripts]
ros-core = "ros_core:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "opencv-stubs==0.1.3",
]